### PR TITLE
Closes #79 rename docker compose folder so that it can work in windows

### LINKED ISSUE #79: Docker Solution for Windows 10 Home Users
Currently Windows 10 Home users aren't able to (easily) run Docker/ docker-compose and run the server locally. 

Acceptance Criteria:
Windows 10 Home users can run server locally via docker, instructions are easy to follow on readme

Possible solutions:
- Install Linux (either dual boot or VM)
- Subsidise upgrades to Win PRO
- Figure out a clean process for docker toolbox
- Host server remotely so that not everyone needs to run server locally?

### PR DESCRIPTION
**Pull request by Foreverflying**
add some instruction to Readme.md on doing docker things in windows 10 home edition.

### CODE REVIEW

**Comment by stanley-roache** [comment]
@Foreverflying On my machine this solves one of the problems for docker-compose on windows, the centripetal-dev/centripetaldev network name. 

The problem of .sh scripts not running properly because of the CLRF/LF/CR line breaks means I still can't get the intialisation scripts to run with docker-compose. Does this have a fix?

Method 2 using docker without docker-compose works though, do you think we direct windows 10 home users to do this?

**Comment by Foreverflying** [comment]
git config --local core.autocrlf input

**Comment by Foreverflying** [comment]
I've add a new file .gitattributes, which can help us regulate the EOL automatically when we do commit.
More tests is required, I do not have windows machine now.
I suggest to clean your local git repo first, re-clone a new one.

**Comment by stanley-roache** [comment]
Awesome awesome. I will test again with a clean repo and let you know how it goes

**Comment by stanley-roache** [comment]
@Foreverflying I did a clean clone and tested, I still run into the same problems.

Then I tried adding a blank line to each of the .sh files and recommiting on a test branch in case recommiting resets the end of line characters, still same error

I also tried the command you suggested, got the same thing.

Could this be something to do with my settings? I vaguely remember when setting up git bash on windows it asked me about CL/CLRF settings.... I don't recall what I did. I guess we want it to work either way

**Comment by Foreverflying** [comment]
ah, sorry for that, i'll have a try on my win machine at home. i have tried yesterday, and everything is working. i guess my global config for git is correct, which sets core.autocrlf to input. this behavior can be easily tested. and the .gitattributes file isn't supported by some version of git like egit or jgit

**Comment by Foreverflying** [comment]
anyhow, the local setting should work but it doesn't. i'll figure this out

**Pull request merged**
