### PR TITLE
add a pgadmin docker compose

### PR DESCRIPTION
**Pull request by Foreverflying**
more work on #36 
add a PGAdmin tool to see the details of postgresSQL

### CODE REVIEW

**Comment by chasm** [comment]
Looks good to me. Does it work?

**Comment by stanley-roache** [comment]
@Foreverflying  

I did this:
- run postgraphile server in background
- go into docker/pgadmin and follow instructions
- got to localhost:5050 ( pgadmin4 runs!!!!)

I run into problems when I try to create new server and connect to db:

**Unable to connect to server:

could not translate host name "host.docker.internal" to address: Name does not resolve**

Am I doing something wrong/ is there a missing step? Am I supposed to run server in background or does that break something?

**Comment by Foreverflying** [comment]
@stanley-roache 
hi Stanley, the host name 'host.docker.internal' is supported from the docker version 18, will you please check your docker's version?

**Comment by Foreverflying** [comment]
I've created another docker-compose file, to make initiating postgres easier.

**Comment by Foreverflying** [comment]
@chasm
yes, it works on my mac, with docker version 18.09
need more feedback~

**Comment by stanley-roache** [comment]
@Foreverflying docker --version gives:

Docker version 18.09.0, build 4d60db4

Maybe its a linux specific issue

**Comment by stanley-roache** [comment]
I think that's the case:

https://github.com/docker/for-linux/issues/264

**Comment by Foreverflying** [comment]
@stanley-roache 
ah, what a pity, I need this feature in the new way of initiating postgres

**Comment by stanley-roache** [comment]
@Foreverflying Yea I got the same error when I ran the new instructions after your last commit. Dam, that's annoying.

Am I understanding right that docker.host.internal is only needed if there are separate .yml files? Is it possible to combine the 3 .yml files? Maybe not ideal

**Comment by Foreverflying** [comment]
@stanley-roache 
would you try using 172.17.0.1 instead, does it work?
172.17.0.1 is a magic ip address which indicates the host.
but I guess we shouldn't rely on it, we can use it temporarily before host.docker.internal is supported on all the platforms

**Comment by Foreverflying** [comment]
it's a problem of docker-compose, which doesn't support partially up - every container in the yml file have to start together. Or else we can put all the containers together in one yml file, and start some of them when up, and manually start others when we need them.

**Comment by stanley-roache** [comment]
@Foreverflying yes that works

**Comment by stanley-roache** [comment]
But just for pgadmin4, I don't know how to do the equivalent for the new postgres method

**Comment by Foreverflying** [comment]
you inspired me. yes actually we can make all the ymls use one same network

**Comment by Foreverflying** [comment]
it works now, without using host.docker.internal.
and, if now you uncomment the client lines in the docker-compose.yml, it will start the client in docker as well. the high cpu usage problem seems disappeared.
(before you do this, you should remove your node_modules folder first, then when it started, it will run yarn in linux environment which in docker.)
but for now, I didn't find a way to remote debug the project which started by 'react-scripts start'.
so I just left it as before.

**Comment by stanley-roache** [comment]
@Foreverflying nice nice, this works on my machine. The client container part works too, that's pretty slick.

I'd be in favour of keeping the client container commented for now as you've done, even a small change to how the development environment for the client side works would impact everyone so IMO that should be rock solid before introducing. Would be pretty awesome though

Not able to test this on windows machine (I've got home so there are already problems with the docker-compose scripts) maybe someone else could check that.

**Comment by stanley-roache** [comment]
@Foreverflying I suspect @chasm might want eyes on this again once more before merge

**Comment by Foreverflying** [comment]
@chasm 
Er... sorry for do merge myself.
have a look at the changing please, I guess most of them doesn't affect other parts of code.

**Pull request merged**
