### PR TITLE
update .gitattributes to regulate the eol.

### PR DESCRIPTION
**Pull request by Foreverflying**
continue PaperHat/centripetal#103
last time the .gitattributes file doesn't configured correctly, a new fix is here. it works on windows now.
add some instructions for windows 10 home edition users.

### CODE REVIEW

**Comment by Foreverflying** [comment]
@stanley-roche
Yes you're right,  I updated the readme.md in this commit too,  added some more instructions on how to resolve this  problem, as well some other problems related with docker on the Windows 10 home edition.

**Comment by stanley-roache** [comment]
hmmm, I think I followed all the changed instructions in this branch and I am still getting the error, I might have missed a part, should the port forwarding fix this?

**Comment by Foreverflying** [comment]
Did you started the docker as Administrator?

**Comment by Foreverflying** [comment]
You can type
docker-compose logs -f server
to see what happened in it.

**Comment by stanley-roache** [comment]
server_1  | +
server_1  | /home/node/wait_to_start_project.sh: 2: /home/node/wait_to_start_project: not found
server_1  | + project_path=packages/server
server_1  | + start_script=start
server_1  | + wait_sec=2
server_1  | + wait_host=
server_1  | + wait_port=
server_1  | +
server_1  | /home/node/wait_to_start_project.sh: 8: /home/node/wait_to_start_project: not found
server_1  | + echo usage:
server_1  | usage:
server_1  | + echo wait_to_start_project.sh <project_path> [wait_sec] [wait_host <wait_port>]
server_1  | wait_to_start_project.sh <project_path> [wait_sec] [wait_host <wait_port>]
server_1  | + exit
server_1  | /home/node/wait_to_start_project.sh: 12: /home/node/wait_to_start_projec: not found
server_1  | + }
server_1  | /home/node/wait_to_start_project.sh: 13: /home/node/wait_to_start_projec: not found
server_1  | +
server_1  | /home/node/wait_to_start_project.sh: 14: /home/node/wait_to_start_projec: not found
server_1  | /home/node/wait_to_start_project.sh: 41: /home/node/wait_to_start_project.sh: Syntax error: end of file unexpected (expecting "then")

**Comment by Foreverflying** [comment]
@stanley-roache 
I guess you need to run ```docker-compose build``` first, to update your local docker image.

**Comment by stanley-roache** [comment]
hmmm, I rebuilt both the image-node-dev image and the postgres-pg-rrule images with the command:
```docker build -t <name_of_folder> --no-cache .```
from inside directory image-node-dev/ postgres-pg-rrule. If I understand right that rebuilds the server image and (although not necessary) the database image

Then I ran the instructions from the start, I still got the same thing. Not sure what's going on, I will probably stop trying things now but be back online for a bit 27th/28th

**Comment by Foreverflying** [comment]
use ```docker-compose build``` instead.

for the docker-compose up will check the image named in the compose file. if there's an image with this name exists,  It won't update the image.

**Comment by stanley-roache** [comment]
@Foreverflying ah, I misread and rushed my apologies. Tried again and it works great on my machine. Awesome

**Comment by Foreverflying** [comment]
@chasm please help to merge this branch, thank you!

**Pull request merged**
